version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    restart: always
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  
  user-mongo:
    image: mongo
    container_name: user-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: usersdb
      MONGO_USERNAME: user
      MONGO_PASSWORD: userpassword
    volumes:
      - user-mongo-data:/data/db
    

  user-service:
    build: ./user
    container_name: user-container
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - user-mongo


  product-mongo:
    image: mongo
    container_name: product-mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: usersdb
      MONGO_USERNAME: user
      MONGO_PASSWORD: userpassword
    volumes:
      - product-mongo-data:/data/db


  product-service:
    build: ./product
    container_name: product-service
    ports:
      - "3001:3001"
    depends_on:
      - kafka
      - product-mongo

  order-mongo:
    image: mongo
    container_name: order-mongo
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: usersdb
      MONGO_USERNAME: user
      MONGO_PASSWORD: userpassword
    volumes:
      - order-mongo-data:/data/db

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka
      - order-mongo

  cart-mongo:
    image: mongo
    container_name: cart-mongo
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: usersdb
      MONGO_USERNAME: user
      MONGO_PASSWORD: userpassword
    volumes:
      - cart-mongo-data:/data/db
  
  cart-service:
    build: ./cart
    container_name: cart-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
      - cart-mongo

volumes:
  user-mongo-data:
  product-mongo-data:
  cart-mongo-data:
  order-mongo-data:
